### ISSUE TITLE
    public function getVat()     {

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-cart#10]
It seems that you forgot to specify that getVat needs to be implemented in your docs

**Comment by igor-chepurnoi** [comment]
// returns the sum of all 'vat' attributes (or return values of getVat()) from all models in the cart.

$totalVat = $cart->getAttributeTotal('vat');

**Comment by igor-chepurnoi** [comment]
This comment already implemented in docs

**Comment by robov** [comment]
I do not see it... 
`
2) Create the Product Model that implements an CartItemInterface:

class ProductModel extends ActiveRecord implements CartItemInterface
{

    public function getPrice()
    {
        return $this->price;
    }

    public function getLabel()
    {
        return $this->name;
    }

    public function getUniqueId()
    {
        return $this->id;
    }
}
`
