### ISSUE TITLE
Table wrong reference

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-cart#11]
ase table or view not found: 1146 Table 'mxcom0_dev.cart' doesn't exist
The SQL being executed was: SELECT `cartData` FROM `cart` WHERE `sessionId`=1
Error Info: Array

It looks for a table named 'cart' however the migration creates the correct 'prefix_cart'
So I guess there is a missing prefix in the code somewhere

**Comment by igor-chepurnoi** [comment]
I fix this issue, you can update your package and try again.
