### ISSUE TITLE
Docs getUniqueId

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-cart#12]
Please explain that this is a Unique Id for the cartitem. not the product  itself.
So if I have 1 product, 4 times added, there should be 4 different unique ID's

I am trying to help out, not to critisize your work.... hope you appreciate it

**Comment by igor-chepurnoi** [comment]
Common way use the id of product, but you can use id field + hash for example.

**Comment by robov** [comment]
I used the productID , but then I could only add 1 of that product in the cart.

**Comment by igor-chepurnoi** [comment]
Then you need add some hash for this products

**Comment by robov** [comment]
I know... it is good to explain that in the doc

**Comment by igor-chepurnoi** [comment]
If you want you can read about pull requests in github and create PR for it.
