### ISSUE TITLE
QTY ?

### ISSUE THREAD

**Issue by robov** [yii2mod/yii2-cart#13]
Is there a possiblity to add a product and order it 6 times ? I seem to be able to only add 1 product at a time, and that multiple qty show on different lines

**Comment by igor-chepurnoi** [comment]
You can add as many products as you want, but you need to use unique id for this products.

**Comment by robov** [comment]
Yes I saw...
I expected 
"productA  4x  $100    = $400"

Your cart shows
"productA   $100"
"productA   $100"
"productA   $100"
"productA   $100"

So if I order 1000 screws... that would be a looong cart....

**Comment by igor-chepurnoi** [comment]
You can overwrite the cart view and create your own dataprovider with GridView

**Comment by robov** [comment]
Ok, I will.. thanks
