### ISSUE TITLE
how to add and retrive information from cart? 

### ISSUE THREAD

**Issue by Alionides** [yii2mod/yii2-cart#16]
Hello. i have installed extension and also migration as well but widget shows empty data id , label and price. how to add product to cart? also in migration there is no any product table added to database.

**Comment by igor-chepurnoi** [comment]
1. You need to create your own product table and then create product model, for example:
```php
class ProductModel extends ActiveRecord implements CartItemInterface
{

    public function getPrice()
    {
        return $this->price;
    }

    public function getLabel()
    {
        return $this->name;
    }

    public function getUniqueId()
    {
        return $this->id;
    }
}
```

2. Add, retrieve, clear operations
```php
// access the cart from "cart" subcomponent
$cart = \Yii::$app->cart;

// Product is an AR model implementing CartProductInterface
$product = Product::findOne(1);

// add an item to the cart
$cart->add($product);

// returns the sum of all 'vat' attributes (or return values of getVat()) from all models in the cart.
$totalVat = $cart->getAttributeTotal('vat');

// clear the cart
$cart->clear();
```

**Comment by Alionides** [comment]
my tables name should be 'product'  ? how i need to name product tables columns?

**Comment by igor-chepurnoi** [comment]
The name of the product table does not matter, required columns - id, name, price

**Comment by Alionides** [comment]
i added table with name product  with following columns. but i dont know what to do next in controller. how to connect my table to this extension. if you have any project built on this extension may i look at?

**Comment by igor-chepurnoi** [comment]
1. You need to create few products in the database, just for testing, manually.
2. If you need to display cart items, you need to create basic action and view file, for example:

**Controller**

```php
/**
 * Class SiteController
 */
class SiteController extends Controller
{
    /**
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}
```

**View file: index.php**

```php
<?php echo \yii2mod\cart\widgets\CartGrid::widget([
    'cartColumns' => [
        'id',
        'label',
        'price'
    ]
]);

```

**Comment by igor-chepurnoi** [comment]
**Add products to cart**

1. Basically, you need to create two actions, first action for display list of products and the second for add product to your cart, for example:

```php
/**
 * Class CatalogController
 */
class CatalogController extends Controller
{
    /**
     * Displays products page.
     *
     * @return mixed
     */
    public function actionList()
    {
        return $this->render('index');
    }

    /**
     * Add product to cart.
     *
     * @param $id Product ID
     *
     * @return \yii\web\Response
     */
    public function actionAdd($id)
    {
        $product = $this->findModel($id);

        $cart = \Yii::$app->cart;

        // add an item to the cart
        $cart->add($product);

        // flash message
        \Yii::$app->session->setFlash('success', 'Product has been added to your cart.');

        return $this->redirect(['list']);
    }

    /**
     * Find Product
     *
     * @param $id
     *
     * @return mixed
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
```

**Comment by Alionides** [comment]
i did what you said. but no results found. maybe im using ```
'storageClass' => [
                'class' => 'yii2mod\cart\storage\DatabaseStorage',
                // you can also override some properties 
                'deleteIfEmpty' => true
            ]
```

i have test product records in product table.

**Comment by igor-chepurnoi** [comment]
Do you have any products in your database?

**Comment by Alionides** [comment]
yes sure i have added them manually to db

**Comment by igor-chepurnoi** [comment]
Can you show your code for this page and your view file?

**Comment by Alionides** [comment]
this is my sitecontroller
```
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Cookie;
use app\models\Product;



class SiteController extends Controller
{
    public function behaviors()
    {
        return [
        'access' => [
        'class' => AccessControl::className(),
    //     'denyCallback' => function ($rule, $action) {
    //     throw new \Exception('Bu səhifəyə girişiniz icazə verilmir!');
    // },
        'only' => ['admin'],
        'rules' => [
        [
                        //'actions' => ['logout'],
        'allow' => true,
        
         'roles' =>['admin','@'],// qeydiyatdan kecen adminler ucun
         //'roles' =>['@'], // umumi qeydiyatdan kecen userler ucun 

        ],
        ],
        ],
        'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
                    //'logout' => ['post'],
        ],
        ],
        ];
    }

    public function actions()
    {
        return [
        'error' => [
        'class' => 'yii\web\ErrorAction',
        ],
        'captcha' => [
        'class' => 'yii\captcha\CaptchaAction',
        'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
        ],
        ];
    }

    public function actionProductadd(){


        return $this->render('productadd');
    }
     public function actionList()
    {
        return $this->render('index');
    }

    /**
     * Add product to cart.
     *
     * @param $id Product ID
     *
     * @return \yii\web\Response
     */
    public function actionAdd($id)
    {
        $product = $this->findModel($id);

        $cart = \Yii::$app->cart;

        // add an item to the cart
        $cart->add($product);

        // flash message
        \Yii::$app->session->setFlash('success', 'Product has been added to your cart.');

        return $this->redirect(['list']);
    }

    /**
     * Find Product
     *
     * @param $id
     *
     * @return mixed
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
```


/////this is my product model

`<?php

namespace app\models;

use Yii;

class ProductModel extends ActiveRecord implements CartItemInterface
{

    public static function tableName()
    {
        return 'product';
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function getLabel()
    {
        return $this->name;
    }

    public function getUniqueId()
    {
        return $this->id;
    }
}`

**Comment by igor-chepurnoi** [comment]
And please show code of your view files

**Comment by Alionides** [comment]
when i enter url localhost/project/site/add/1 it doesnt add any thing. in 1 id there is a product in product table it should add without view file i think. i didnt create view file.

**Comment by igor-chepurnoi** [comment]
Check your cart by this code
```php
$cart = \Yii::$app->cart;

// get all items from the cart
$items = $cart->getItems();

var_dump($items);
die;
```
What does this code show?

**Comment by Alionides** [comment]
i aded it only says page not found. 
if its action it should give error o show some data. why it says page not fount i dont know

**Comment by Alionides** [comment]
there are 2 actions first one is giving hello response but second action gives page not found. 


 public function actionAaa(){

        echo "hello";
    }
    
public function actionProducttest(){
    $cart = \Yii::$app->cart;

// get all items from the cart
$items = $cart->getItems();

var_dump($items);
die;
}

**Comment by Alionides** [comment]
i changed action name to easy one it gave me this response 

`array(0) { } `

**Comment by igor-chepurnoi** [comment]
Give me few minutes please, I'll install this package

**Comment by Alionides** [comment]
thank you for your big effort to help me. i wanted to do it manually everything but why to create a bicycle if it exists .

**Comment by igor-chepurnoi** [comment]
I have installed this package.

1. I created Product model, with the following content:
```php
<?php

namespace frontend\models;

use yii\db\ActiveRecord;
use yii2mod\cart\models\CartItemInterface;

/**
 * Class Product
 * @package frontend\models
 */
class Product extends ActiveRecord implements CartItemInterface
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @return mixed
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @return mixed
     */
    public function getLabel()
    {
        return $this->name;
    }

    /**
     * @return mixed
     */
    public function getUniqueId()
    {
        return $this->id;
    }
}
```

2. I have added this code to my application configuration
```php
'components' => [
        'cart' => [
            'class' => 'yii2mod\cart\Cart',
            'storageClass' => [
                'class' => 'yii2mod\cart\storage\DatabaseStorage',
            ],
        ],
],
```

3. I create `ProductController` with the following code

```php
<?php

namespace frontend\controllers;

use frontend\models\Product;
use yii\web\Controller;

/**
 * Class ProductController
 *
 * @package frontend\controllers
 */
class ProductController extends Controller
{
    /**
     * Displays product page.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        // access the cart from "cart" subcomponent
        $cart = \Yii::$app->cart;

        // Product is an AR model implementing CartProductInterface
        $product = Product::findOne(1);

        // add an item to the cart
        $cart->add($product);

        var_dump($cart->getItems());
        die("111");
    }
}
```

After this steps, I followed to url `product/index`. See below screenshot

http://awesomescreenshot.com/0546d2e0a3

**Comment by Alionides** [comment]
i think something wrong with my yii2 project  it gives me Not Found (#404)  .   every pice of code is same as yours. some actions give me this error i dont know why

**Comment by igor-chepurnoi** [comment]
Check your url manager configuration, here is mine
```php
    'urlManager' => [
        'enablePrettyUrl' => true,
        'showScriptName' => false,
        'rules' => [
            '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            '<module:\w+>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',
        ],
    ],
```

**Comment by igor-chepurnoi** [comment]
My table - http://pix.toile-libre.org/upload/original/1503906486.png

**Comment by Alionides** [comment]
mine is this 

`'urlManager' => [
                'enablePrettyUrl' => true,
                'showScriptName' => false,
                'rules' => [],
            ///////////////////////////////////////////
                'class' => 'codemix\localeurls\UrlManager',

            // List all supported languages here
            // Make sure, you include your app's default language.
                'languages' => ['az', 'en', 'ru'],
                ],`

**Comment by igor-chepurnoi** [comment]
My table - http://pix.toile-libre.org/upload/original/1503906486.png

**Comment by igor-chepurnoi** [comment]
Add to your `rules` the following code
```php
        'rules' => [
            '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            '<module:\w+>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',
        ],
```

**Comment by igor-chepurnoi** [comment]
After this changes, try your action again

**Comment by Alionides** [comment]
same error  result page not found

**Comment by Alionides** [comment]
if you have teamviewer i can give u access to see it real

**Comment by igor-chepurnoi** [comment]
I'm at work now and I can't help at this time, sorry :(

**Comment by igor-chepurnoi** [comment]
Also you can try install fresh yii2 application, and try this code

**Comment by igor-chepurnoi** [comment]
I don't have any ideas now

**Comment by Alionides** [comment]
okay thank you again u did a lot maybe you can close this issue i will try ti fix it out myself.

**Comment by igor-chepurnoi** [comment]
You're welcome. When you will fix this error, let me know. Thanks.

**Comment by Alionides** [comment]
okay i will let you know when i do it

**Comment by Alionides** [comment]
i found solution the url with id i didnt call correctly it should be like http://localhost/project/web/az/site/product?id=1

**Comment by igor-chepurnoi** [comment]
Perfect!

**Comment by Alionides** [comment]
it worked also retrived data from db as well. thank you very much.

**Comment by igor-chepurnoi** [comment]
You're welcome, have a nice day!
