### ISSUE TITLE
Dynamic Price ( Price method POST )

### ISSUE THREAD

**Issue by prabukarana** [yii2mod/yii2-cart#20]
How ,i can send parameter qty , price and packaging.
And Price is depends by packaging
Example.
$id = $model->id
$product = MBarang::findOne($id);
$price = $model->price
$packaging = $model->packaging
$qty = $model->qty

**Comment by igor-chepurnoi** [comment]
Hi, this package doesn't provide any HTTP controllers, you need to create your own action class with your custom logic.

**Comment by prabukarana** [comment]
Thx to reply igor,
I create my own controller, with post method. 

$id = $model->id
$price = $model->price
$product = Product::findOne($id)
$cart->add($product);

so how, i can post the price like $cart->price($price). 
Can you give me a idea..
thx..

**Comment by igor-chepurnoi** [comment]
I think you don't need to post the price because cart object retrieves this information from your model. For example in this widget:

```php
<?php echo \yii2mod\cart\widgets\CartGrid::widget([
    // Some widget property maybe need to change. 
    'cartColumns' => [
        'id',
        'label',
        'price'
    ]
]); ?>
```

**Comment by prabukarana** [comment]
Hi, 
But unfortunately... The price is depends by User choice. 
Example user can choice small pack or big pack. Small or Big pack have diferent price.

That why i need to post the price.

There is solution,
1. Post the price, or
2. post the packaging

**Comment by igor-chepurnoi** [comment]
Ok, Also you can try this package https://github.com/omnilight/yii2-shopping-cart

**Comment by igor-chepurnoi** [comment]
Maybe it's more flexible solution for your case

**Comment by prabukarana** [comment]
Hi.. thx Igor..
Im already using that ext, but still confuse  using it when post the price.
