### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by iridance** [yii2mod/yii2-cart#21]
system: windows 10 16299.64
database: PostgreSql9.1

> in path\vendor\yiisoft\yii2\db\Schema.php:636

Error Info:
Array
(
    [0] => 42601
    [1] => 7
    [2] => ERROR:  syntax error at or near "`"
LINE 4:  PRIMARY KEY (`sessionId`)
                      ^
)

I tried to modify this file after the success

$this->createTable('{{%Cart}}', [
            'sessionId' => $this->string(),
            'cartData' => $this->text(),
], $tableOptions);
$this->addPrimaryKey('cart_primary_key', '{{%Cart}}', 'sessionId');

**Comment by igor-chepurnoi** [comment]
Can you create pull request for this issue?
