### ISSUE TITLE
Calling unknown method: yii2mod\cart\Cart::getSession()

### ISSUE THREAD

**Issue by PaulAsfalt** [yii2mod/yii2-cart#4]
```
'components' => [
        'cart' => [
            'class'          => 'yii2mod\cart\Cart',
            'storageClass' => 'yii2mod\cart\storage\DatabaseStorage'
        ],
]
```

**Comment by igor-chepurnoi** [comment]
Hi, thanks for issue. Issue was fixed and the documentation has been updated.  Please try to update the package via composer.

**Comment by PaulAsfalt** [comment]
Hi, thanks for the module. But I'm not going to use 'yii2mod\cart\storage\DatabaseStorage'. 
Use "REPLACE" only valid for mysql. 

My test code for postgresql v9.5:
```
 $command->setSql("
                INSERT INTO {$this->table}
                ({$this->idField}, {$this->dataField})
                VALUES (:id, :val)
                ON CONFLICT ({$this->idField}) 
                DO UPDATE SET {$this->dataField} = EXCLUDED.{$this->dataField}
            ")->bindValues([
                ':id' => $identifier,
                ':val' => $sessionData,
            ]);
```

Why DatabaseStorage does not extends ActiveRecord?
The class CartItemInterface contains a new method getPrice(). The basket may contain items which have no prices. The basket is not necessarily used for the store - this is my thought.

**Comment by igor-chepurnoi** [comment]
Yes, I agree with you. I think that we can rewrite the `save` function in the `DatabaseStorage` for more compatibility with other databases.

**Comment by igor-chepurnoi** [comment]
I agree with you to a certain extent. But, i think that the `basket` more often used for purchases of products that have a price. If product without price, we can use the following code for skip it:
```php
    public function getPrice()
    {
        return null;
    }
```

What do you think about it?

**Comment by igor-chepurnoi** [comment]
> The class CartItemInterface contains a new method getPrice(). The basket may contain items which have no prices. The basket is not necessarily used for the store - this is my thought.

**Comment by PaulAsfalt** [comment]
will have to do
```
public function getPrice()
    {
        return null;
    }
```

In php-postgresql problem:
https://github.com/yiisoft/yii2/issues/10823
https://bugs.php.net/bug.php?id=53756

while solved so:
```
base64_encode(serialize($items))
unserialize(base64_decode($items))
```

**Comment by igor-chepurnoi** [comment]
Hi,
>  In php-postgresql problem:
> yiisoft/yii2#10823
> https://bugs.php.net/bug.php?id=53756

> while solved so:

> base64_encode(serialize($items))
> unserialize(base64_decode($items))


Can you create pull request for this problem?

**Comment by PaulAsfalt** [comment]
This is bug of php. This is a temporary solution of problem. It does not deserve pull request :).

I would in future releases recommended methods: toggleItem (or toggle) and findItem (or find). 
Now not very convenient to use by adding and removing from the basket a single item, if you don't know is it in the basket or not.

**Comment by PaulAsfalt** [comment]
And how to understand successfully whether the added or deleted item from cart?

**Comment by igor-chepurnoi** [comment]
> And how to understand successfully whether the added or deleted item from cart?

Both functions return an object "Cart" and at the moment I don't know how to implement it.

**Comment by igor-chepurnoi** [comment]
But, i think we can add the exeption when item was not be saved to the cart, for example we can modify `add` function like this:
```php
if(($save && $this->storage->save($this)) === false)  {
   
}
```
