### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by ApXaHgheJI** [yii2mod/yii2-cart#7]
The problem that my model have an annonymouce functions.
and there is no possibility to avoid this use case...

**Comment by igor-chepurnoi** [comment]
Hi, can you create PR for this use case?

**Comment by ApXaHgheJI** [comment]
PR ? не совсем тебя понял Игорь - но я уже удалил и нашел другой.
Проблема в том что ты сериализуешь модель - а в ней есть аннонимные функций.. ( что я создаю на лету ) так вот на это и ругается.

**Comment by igor-chepurnoi** [comment]
> не совсем тебя понял Игорь

Я имел ввиду пулл реквест
> но я уже удалил и нашел другой.

окей
> Проблема в том что ты сериализуешь модель - а в ней есть аннонимные функций.. ( что я создаю на лету ) так вот на это и ругается.

спасибо за issue, как будет возможность постараюсь исправить.
